/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107268-g42d75f2faa-20220629"
#endif /* AVUTIL_FFVERSION_H */
